apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: open-elevation-api-claim0
  name: open-elevation-api-claim0
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
