apiVersion: v1
kind: Service
metadata:
  annotations:
    com.centurylinklabs.watchtower.enable: "false"
  labels:
    io.kompose.service: open-elevation-api
  name: open-elevation-api
spec:
  ports:
    - name: "8989"
      port: 8989
      targetPort: 8080
  selector:
    io.kompose.service: open-elevation-api
  type: ClusterIP
  externalIPs:
    - 10.10.0.240
