apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: open-elevation-api-claim1
  name: open-elevation-api-claim1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ki
