apiVersion: v1
kind: Service
metadata:
  annotations:
    com.centurylinklabs.watchtower.enable: "false"
  labels:
    io.kompose.service: open-elevation-api
  name: open-elevation-api
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: open-elevation-api
  type: ClusterIP
